import OPKTerminalCore
import OPKTerminalOperator

enum TerminalReadiness: Equatable {
    case walletRequired
    case configurationRequired
    case operatorBindingMismatch
    case validationRequired
    case statusCheckRequired
    case authorizationRequired
    case gasRequired(available: UInt256)
    case ready

    static let minimumGasBalance = UInt256(100_000_000_000_000)

    var isReady: Bool { self == .ready }

    var title: String {
        switch self {
        case .walletRequired: "Create operator wallet"
        case .configurationRequired: "Scan portal setup QR"
        case .operatorBindingMismatch: "Operator binding changed"
        case .validationRequired: "Validate configuration"
        case .statusCheckRequired: "Check operator status"
        case .authorizationRequired: "Awaiting vault authorization"
        case .gasRequired: "Awaiting gas funding"
        case .ready: "Terminal ready"
        }
    }

    var detail: String {
        switch self {
        case .walletRequired:
            "Create the device-local operator before pairing this terminal."
        case .configurationRequired:
            "Scan the provisioning QR generated by the merchant portal."
        case .operatorBindingMismatch:
            "Reprovision with a QR bound to this device's current operator."
        case .validationRequired:
            "The deployment and token must pass fresh on-chain validation."
        case .statusCheckRequired:
            "Refresh the on-chain authorization and native balance."
        case .authorizationRequired:
            "Grant this EOA owner/operator access from the merchant portal."
        case let .gasRequired(available):
            "Fund the operator to at least \(Self.minimumGasBalance.decimalString) wei; current balance is \(available.decimalString) wei."
        case .ready:
            "Configuration, operator authorization, and gas are ready for a new payment QR."
        }
    }

    var systemImage: String {
        switch self {
        case .ready: "checkmark.shield.fill"
        case .gasRequired: "fuelpump.fill"
        case .authorizationRequired, .operatorBindingMismatch: "xmark.shield.fill"
        case .validationRequired, .statusCheckRequired: "arrow.clockwise.circle"
        case .walletRequired: "key.fill"
        case .configurationRequired: "qrcode.viewfinder"
        }
    }

    static func evaluate(
        settings: AppSettings,
        operatorAddress: EthereumAddress?,
        validatedFingerprint: String?,
        operatorStatus: OperatorChainStatus?
    ) -> TerminalReadiness {
        guard let operatorAddress else { return .walletRequired }
        guard settings.isProvisioned else { return .configurationRequired }
        guard let bound = settings.provisionedOperatorAddress,
              let boundAddress = try? EthereumAddress(hex: bound, allowZero: false),
              boundAddress == operatorAddress
        else { return .operatorBindingMismatch }
        guard validatedFingerprint == settings.validationFingerprint else {
            return .validationRequired
        }
        guard let operatorStatus,
              String(operatorStatus.chainID) == settings.chainID
        else { return .statusCheckRequired }
        guard operatorStatus.isAuthorizedOperator else { return .authorizationRequired }
        guard operatorStatus.balance >= minimumGasBalance else {
            return .gasRequired(available: operatorStatus.balance)
        }
        return .ready
    }
}
